export const INIT_SHELF = 'INIT_SHELF';
export const ADD_SHELF = 'ADD_SHELF';
export const EDIT_SHELF = 'EDIT_SHELF';
export const REMOVE_SHELF = 'REMOVE_SHELF';

export const RELEASES_FETCH = 'RELEASES_FETCH';
export const RELEASES_FETCH_SUCCESS = 'RELEASES_FETCH_SUCCESS';