export const INIT_SHELF = 'INIT_SHELF';
export const ADD_SHELF = 'ADD_SHELF';
export const EDIT_SHELF = 'EDIT_SHELF';
export const REMOVE_SHELF = 'REMOVE_SHELF';
export const RENDER_SHELVES = 'RENDER_SHELVES';

export const RELEASES_FETCH = 'RELEASES_FETCH';
export const RELEASES_FETCH_NEXT = 'RELEASES_FETCH_NEXT';
export const RELEASES_FETCH_SUCCESS = 'RELEASES_FETCH_SUCCESS';

export const IS_LOADING = 'IS_LOADING';
export const DONE_LOADING = 'DONE_LOADING';